// Generated by tools/make_swiftpm.py from App/RPPG/Capture/CameraSession.swift — do not edit here.
import AVFoundation
import Foundation
import os

/// Front-camera capture configured for photoplethysmography rather than for looking
/// good.
///
/// Three settings matter more than anything else in this file, and all three exist to
/// stop the camera from "helpfully" removing the signal:
///
/// * **Exposure and white balance are locked** once the scene has settled. Continuous
///   auto-exposure chases the same 1%-of-DC intensity change the pulse lives in and
///   flattens it.
/// * **HDR / tone mapping is disabled** — it is a non-linear, frame-dependent
///   transform of exactly the quantity being measured.
/// * **Frame duration is pinned** min == max, so the sample rate the DSP assumes is
///   the sample rate it actually gets.
/// `@unchecked Sendable`: every mutable property is confined to `sessionQueue`,
/// and `onFrame` is set once before the session starts.
final class CameraSession: NSObject, @unchecked Sendable {

    struct Configuration {
        /// Frame rate to request. The highest rate the chosen format supports at or
        /// below this value is used.
        var targetFrameRate: Double = 60
        /// Preferred capture width. Higher resolutions only cost bandwidth: the ROI is
        /// spatially averaged anyway.
        var preferredWidth: Int32 = 1280
        /// How long to let auto-exposure converge before locking it.
        var autoLockDelay: TimeInterval = 2.0
        var lockExposure: Bool = true
        var lockWhiteBalance: Bool = true
        var disableHDR: Bool = true
    }

    enum StartError: Error, LocalizedError {
        case notAuthorized
        case noFrontCamera
        case configurationFailed(String)

        var errorDescription: String? {
            switch self {
            case .notAuthorized:
                return "Camera access was denied. Enable it in Settings > Privacy > Camera."
            case .noFrontCamera:
                return "No front-facing camera is available on this device."
            case .configurationFailed(let reason):
                return "Camera configuration failed: \(reason)"
            }
        }
    }

    /// Called on `outputQueue` for every delivered frame.
    var onFrame: (@Sendable (CVPixelBuffer, TimeInterval) -> Void)?

    /// Called for every frame the output dropped. Dropped frames are a Stage 1 pass
    /// criterion, so they are counted rather than merely logged.
    var onDrop: (@Sendable () -> Void)?

    let session = AVCaptureSession()

    /// The frame rate actually negotiated with the device. The DSP is configured from
    /// this, not from `Configuration.targetFrameRate`.
    private(set) var actualFrameRate: Double = 30

    private let configuration: Configuration
    private let sessionQueue = DispatchQueue(label: "rppg.camera.session")
    private let outputQueue: DispatchQueue
    private let videoOutput = AVCaptureVideoDataOutput()
    private var device: AVCaptureDevice?
    private var lockWorkItem: DispatchWorkItem?
    private let logger = Logger(subsystem: "com.rppg.tablet", category: "CameraSession")

    init(configuration: Configuration = Configuration(), outputQueue: DispatchQueue) {
        self.configuration = configuration
        self.outputQueue = outputQueue
        super.init()
    }

    // MARK: - Lifecycle

    func requestAuthorization() async -> Bool {
        switch AVCaptureDevice.authorizationStatus(for: .video) {
        case .authorized:
            return true
        case .notDetermined:
            return await AVCaptureDevice.requestAccess(for: .video)
        default:
            return false
        }
    }

    func start() async throws {
        guard await requestAuthorization() else { throw StartError.notAuthorized }
        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
            sessionQueue.async {
                do {
                    try self.configureSession()
                    self.session.startRunning()
                    self.scheduleAutoLock()
                    continuation.resume()
                } catch {
                    continuation.resume(throwing: error)
                }
            }
        }
    }

    func stop() {
        sessionQueue.async {
            self.lockWorkItem?.cancel()
            self.lockWorkItem = nil
            if self.session.isRunning { self.session.stopRunning() }
        }
    }

    /// Re-runs auto-exposure and re-locks it. Exposed so the UI can offer a
    /// "re-balance" button after the lighting changes.
    func relock() {
        sessionQueue.async {
            guard let device = self.device else { return }
            try? device.lockForConfiguration()
            if device.isExposureModeSupported(.continuousAutoExposure) {
                device.exposureMode = .continuousAutoExposure
            }
            if device.isWhiteBalanceModeSupported(.continuousAutoWhiteBalance) {
                device.whiteBalanceMode = .continuousAutoWhiteBalance
            }
            device.unlockForConfiguration()
            self.scheduleAutoLock()
        }
    }

    // MARK: - Configuration

    private func configureSession() throws {
        session.beginConfiguration()
        defer { session.commitConfiguration() }

        session.sessionPreset = .inputPriority   // the chosen activeFormat wins

        let discovery = AVCaptureDevice.DiscoverySession(
            deviceTypes: [.builtInWideAngleCamera],
            mediaType: .video,
            position: .front
        )
        guard let device = discovery.devices.first else { throw StartError.noFrontCamera }
        self.device = device

        session.inputs.forEach(session.removeInput)
        session.outputs.forEach(session.removeOutput)

        let input = try AVCaptureDeviceInput(device: device)
        guard session.canAddInput(input) else {
            throw StartError.configurationFailed("cannot add camera input")
        }
        session.addInput(input)

        videoOutput.videoSettings = [
            kCVPixelBufferPixelFormatTypeKey as String: kCVPixelFormatType_32BGRA
        ]
        // Dropping a late frame is better than falling behind: the DSP assumes a fixed
        // sample rate, and a growing backlog would break that assumption far worse
        // than an occasional missing sample.
        videoOutput.alwaysDiscardsLateVideoFrames = true
        videoOutput.setSampleBufferDelegate(self, queue: outputQueue)
        guard session.canAddOutput(videoOutput) else {
            throw StartError.configurationFailed("cannot add video output")
        }
        session.addOutput(videoOutput)

        try configureFormat(on: device)
        configureConnection()
    }

    /// Picks the format with the highest frame rate at or below the target, breaking
    /// ties by proximity to `preferredWidth`.
    private func configureFormat(on device: AVCaptureDevice) throws {
        var best: (format: AVCaptureDevice.Format, rate: Double)?

        for format in device.formats {
            let description = CMVideoFormatDescriptionGetDimensions(format.formatDescription)
            guard CMFormatDescriptionGetMediaSubType(format.formatDescription)
                    == kCVPixelFormatType_420YpCbCr8BiPlanarFullRange
                    || CMFormatDescriptionGetMediaSubType(format.formatDescription)
                    == kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange else { continue }

            let supported = format.videoSupportedFrameRateRanges
                .map { min($0.maxFrameRate, configuration.targetFrameRate) }
                .max() ?? 0
            guard supported >= 24 else { continue }

            if let current = best {
                let currentWidth = CMVideoFormatDescriptionGetDimensions(current.format.formatDescription).width
                let betterRate = supported > current.rate + 0.5
                let sameRateCloserSize = abs(supported - current.rate) <= 0.5
                    && abs(description.width - configuration.preferredWidth)
                        < abs(currentWidth - configuration.preferredWidth)
                if betterRate || sameRateCloserSize {
                    best = (format, supported)
                }
            } else {
                best = (format, supported)
            }
        }

        guard let chosen = best else {
            throw StartError.configurationFailed("no suitable capture format")
        }

        try device.lockForConfiguration()
        defer { device.unlockForConfiguration() }

        device.activeFormat = chosen.format
        let duration = CMTime(value: 1, timescale: CMTimeScale(chosen.rate.rounded()))
        device.activeVideoMinFrameDuration = duration
        device.activeVideoMaxFrameDuration = duration
        actualFrameRate = chosen.rate.rounded()

        if configuration.disableHDR {
            device.automaticallyAdjustsVideoHDREnabled = false
            if chosen.format.isVideoHDRSupported { device.isVideoHDREnabled = false }
        }
        if device.isFocusModeSupported(.continuousAutoFocus) {
            device.focusMode = .continuousAutoFocus
        }
        if device.isLowLightBoostSupported {
            device.automaticallyEnablesLowLightBoostWhenAvailable = false
        }

        logger.info("capture format \(chosen.format.description, privacy: .public) at \(self.actualFrameRate) fps")
    }

    /// Applies the same orientation and mirroring to the video data output as the
    /// preview layer uses, so a pixel coordinate from Vision maps to the preview with
    /// nothing more than a uniform scale.
    private func configureConnection() {
        guard let connection = videoOutput.connection(with: .video) else { return }
        CaptureGeometry.apply(to: connection)
    }

    private func scheduleAutoLock() {
        lockWorkItem?.cancel()
        let work = DispatchWorkItem { [weak self] in self?.lockExposureAndWhiteBalance() }
        lockWorkItem = work
        sessionQueue.asyncAfter(deadline: .now() + configuration.autoLockDelay, execute: work)
    }

    private func lockExposureAndWhiteBalance() {
        guard let device else { return }
        do {
            try device.lockForConfiguration()
            defer { device.unlockForConfiguration() }
            if configuration.lockExposure, device.isExposureModeSupported(.locked) {
                device.exposureMode = .locked
            }
            if configuration.lockWhiteBalance, device.isWhiteBalanceModeSupported(.locked) {
                device.whiteBalanceMode = .locked
            }
            logger.info("exposure and white balance locked")
        } catch {
            logger.error("could not lock camera: \(error.localizedDescription, privacy: .public)")
        }
    }
}

extension CameraSession: AVCaptureVideoDataOutputSampleBufferDelegate {

    func captureOutput(
        _ output: AVCaptureOutput,
        didOutput sampleBuffer: CMSampleBuffer,
        from connection: AVCaptureConnection
    ) {
        guard let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return }
        let timestamp = CMTimeGetSeconds(CMSampleBufferGetPresentationTimeStamp(sampleBuffer))
        onFrame?(pixelBuffer, timestamp)
    }

    func captureOutput(
        _ output: AVCaptureOutput,
        didDrop sampleBuffer: CMSampleBuffer,
        from connection: AVCaptureConnection
    ) {
        onDrop?()
    }
}
