// swift-tools-version: 5.9

// App Playground manifest — open this folder with Swift Playgrounds on iPadOS to
// build and run the app on the device itself.
//
// GENERATED by tools/make_swiftpm.py. Edit Sources/RPPGCore or App/RPPG and re-run
// the script; do not edit the copies in this folder.
//
// `AppleProductTypes` only exists inside Swift Playgrounds, so this manifest does not
// resolve with command-line SwiftPM. That is expected: the root Package.swift is the
// one `swift build` and `swift test` use.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "RPPG",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "RPPG",
            targets: ["AppModule"],
            bundleIdentifier: "com.rppg.tablet",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "The front camera is used to measure pulse and respiration from small colour changes in the skin. Video is processed on the device and never leaves it.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["README.md"]
        )
    ]
)
