// Generated by tools/make_swiftpm.py from App/RPPG/Views/PassCriterion.swift — do not edit here.
import SwiftUI

/// One row of a stage's pass-criteria checklist: what is required, what was measured,
/// and whether it passes right now.
///
/// The plan's pass criteria live in `docs/PLAN.md` as a table the user fills in by
/// hand. Putting the same table on screen with live values removes the transcription
/// step — and, more usefully, makes it obvious *while adjusting the setup* which
/// criterion is the one still failing.
struct PassCriterion: Identifiable {

    enum Verdict {
        case pass
        case fail
        /// Not enough data yet, or not something the app can judge on its own.
        case pending(String)
    }

    let id = UUID()
    let label: String
    let requirement: String
    let measured: String
    let verdict: Verdict

    init(_ label: String, requirement: String, measured: String, verdict: Verdict) {
        self.label = label
        self.requirement = requirement
        self.measured = measured
        self.verdict = verdict
    }

    /// Convenience for the common numeric case.
    init(
        _ label: String,
        requirement: String,
        value: Double,
        format: String,
        passes: Bool,
        ready: Bool = true,
        pendingNote: String = "measuring…"
    ) {
        self.label = label
        self.requirement = requirement
        self.measured = String(format: format, value)
        self.verdict = ready ? (passes ? .pass : .fail) : .pending(pendingNote)
    }
}

struct PassCriterionList: View {

    let title: String
    let subtitle: String?
    let criteria: [PassCriterion]

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack(alignment: .firstTextBaseline) {
                Text(title)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .textCase(.uppercase)
                Spacer()
                summary
            }
            if let subtitle {
                Text(subtitle)
                    .font(.caption2)
                    .foregroundStyle(.secondary)
            }
            ForEach(criteria) { criterion in
                PassCriterionRow(criterion: criterion)
            }
        }
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
    }

    private var summary: some View {
        let passed = criteria.filter { if case .pass = $0.verdict { return true }; return false }.count
        let failed = criteria.filter { if case .fail = $0.verdict { return true }; return false }.count
        return Text("\(passed)/\(criteria.count) pass" + (failed > 0 ? "  ·  \(failed) fail" : ""))
            .font(.caption.monospacedDigit())
            .foregroundStyle(failed > 0 ? .red : .secondary)
    }
}

struct PassCriterionRow: View {

    let criterion: PassCriterion

    var body: some View {
        HStack(alignment: .top, spacing: 10) {
            icon
                .frame(width: 18)
            VStack(alignment: .leading, spacing: 2) {
                Text(criterion.label)
                    .font(.caption)
                    .foregroundStyle(.primary)
                Text(criterion.requirement)
                    .font(.caption2)
                    .foregroundStyle(.secondary)
            }
            Spacer(minLength: 8)
            Text(measuredText)
                .font(.caption.monospacedDigit())
                .foregroundStyle(tint)
                .multilineTextAlignment(.trailing)
        }
    }

    private var measuredText: String {
        if case .pending(let note) = criterion.verdict, criterion.measured.isEmpty {
            return note
        }
        return criterion.measured
    }

    @ViewBuilder
    private var icon: some View {
        switch criterion.verdict {
        case .pass:
            Image(systemName: "checkmark.circle.fill").foregroundStyle(.green)
        case .fail:
            Image(systemName: "xmark.circle.fill").foregroundStyle(.red)
        case .pending:
            Image(systemName: "clock").foregroundStyle(.secondary)
        }
    }

    private var tint: Color {
        switch criterion.verdict {
        case .pass: return .green
        case .fail: return .red
        case .pending: return .secondary
        }
    }
}
