// Generated by tools/make_swiftpm.py from Sources/RPPGCore/ROISample.swift — do not edit here.
import Foundation

/// One frame's ROI measurement: the `C` vector plus the quality metadata needed to
/// decide whether it should be trusted.
public struct ROISample: Sendable, Equatable {

    /// The specification's `C(1:3,1) = mean(mean(faceimg))`, on the 0–255 scale.
    public var channels: ChannelTriple

    /// Presentation timestamp of the source frame, in seconds.
    public var timestamp: TimeInterval

    /// How many pixels were averaged. A collapsing count means the ROI is drifting off
    /// the frame or the face was lost.
    public var pixelCount: Int

    /// Fraction of averaged pixels with a channel at or near full scale. High values
    /// mean the ROI is blown out and the pulse is being clipped away.
    public var clippedFraction: Double

    public init(
        channels: ChannelTriple,
        timestamp: TimeInterval,
        pixelCount: Int = 0,
        clippedFraction: Double = 0
    ) {
        self.channels = channels
        self.timestamp = timestamp
        self.pixelCount = pixelCount
        self.clippedFraction = clippedFraction
    }

    public static func empty(timestamp: TimeInterval) -> ROISample {
        ROISample(channels: .zero, timestamp: timestamp, pixelCount: 0)
    }

    public var isUsable: Bool { pixelCount > 0 && channels.isUsable }
}
