// Generated by tools/make_swiftpm.py from App/RPPG/RPPGApp.swift — do not edit here.
import SwiftUI

@main
struct RPPGApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
