// Generated by tools/make_swiftpm.py from App/RPPG/RPPGViewModel.swift — do not edit here.
// The two modules are flattened into one App Playground target, so the
// `import RPPGCore` line has been removed.
import Foundation
import SwiftUI
import UIKit

/// Which stage the right-hand panel is showing.
enum PanelMode: String, CaseIterable, Identifiable {
    case tracking = "Tracking"
    case signal = "Signal"

    var id: String { rawValue }
}

/// Which trace the debug plot shows. Every POS intermediate is selectable, because
/// stage-by-stage verification means being able to look at each one on its own.
enum DebugSignal: String, CaseIterable, Identifiable {
    case rppg = "rPPG (H)"
    case rppgFiltered = "rPPG band-passed"
    case respiration = "Respiration (mean corner y)"

    var id: String { rawValue }
}

/// Main-actor face of the capture stack. Holds nothing but published UI state; all the
/// real work lives on ``CaptureCoordinator``'s private queues.
@MainActor
final class RPPGViewModel: ObservableObject {

    @Published private(set) var snapshot = CaptureSnapshot()
    @Published private(set) var isRunning = false
    @Published var errorMessage: String?

    @Published var showsROIOverlay = true
    @Published var showsCornerMarkers = true

    /// More landmarks means a quieter fit; the least rigid ones are the extra ones.
    /// Switch presets and compare the Stage 2 corner-jitter figure.
    @Published var landmarkPreset: FaceTracker.LandmarkPreset = .rigid {
        didSet { coordinator.setLandmarkPreset(landmarkPreset) }
    }
    @Published var panel: PanelMode = .tracking
    @Published var debugSignal: DebugSignal = .rppgFiltered

    @Published var skinGateEnabled = false {
        didSet { coordinator.setSkinGateEnabled(skinGateEnabled) }
    }

    /// 0.8 per the written specification; 1.0 matches the MATLAB reference, which
    /// averages the whole rotated box. Switch to 1.0 for a run being cross-checked.
    @Published var roiScale: Double = 0.8 {
        didSet { coordinator.setROIScale(roiScale) }
    }

    /// URL of the finished recording, presented for export.
    @Published var finishedRecording: URL?

    let coordinator: CaptureCoordinator

    init(coordinator: CaptureCoordinator = CaptureCoordinator()) {
        self.coordinator = coordinator
        coordinator.onSnapshot = { [weak self] snapshot in
            // The coordinator already hops to main; the task only re-establishes the
            // actor isolation the compiler can see.
            Task { @MainActor in self?.snapshot = snapshot }
        }
    }

    // MARK: - Lifecycle

    func start() async {
        guard !isRunning else { return }
        do {
            try await coordinator.start()
            isRunning = true
            errorMessage = nil
            // A measurement runs for tens of seconds with no touch input; without this
            // the tablet dims and auto-locks in the middle of it.
            UIApplication.shared.isIdleTimerDisabled = true
        } catch {
            isRunning = false
            errorMessage = error.localizedDescription
        }
    }

    func stop() {
        guard isRunning else { return }
        coordinator.stop()
        isRunning = false
        snapshot = CaptureSnapshot()
        UIApplication.shared.isIdleTimerDisabled = false
    }

    func resetSignal() {
        coordinator.resetSignal()
        snapshot.rppgWaveform = []
        snapshot.pulseAnalysisWaveform = []
        snapshot.respirationWaveform = []
        snapshot.heartRate = nil
        snapshot.respirationRate = nil
    }

    func rebalanceCamera() {
        coordinator.rebalanceCamera()
    }

    /// Clears the Stage 1 / Stage 2 measurement window.
    func resetStatistics() {
        coordinator.resetStatistics()
    }

    // MARK: - Recording

    func toggleRecording() {
        if snapshot.isRecording {
            coordinator.stopRecording { [weak self] url in
                Task { @MainActor in self?.finishedRecording = url }
            }
        } else {
            do {
                try coordinator.startRecording()
                finishedRecording = nil
            } catch {
                errorMessage = "Could not start recording: \(error.localizedDescription)"
            }
        }
    }

    // MARK: - Display helpers

    var heartRateText: String {
        guard let estimate = snapshot.heartRate, estimate.confidence > 0.25 else { return "--" }
        return String(format: "%.0f", estimate.ratePerMinute)
    }

    var respirationRateText: String {
        guard let estimate = snapshot.respirationRate, estimate.confidence > 0.25 else { return "--" }
        return String(format: "%.0f", estimate.ratePerMinute)
    }

    var debugSamples: [Double] {
        switch debugSignal {
        case .rppg: return snapshot.rppgWaveform
        case .rppgFiltered: return snapshot.pulseAnalysisWaveform
        case .respiration: return snapshot.respirationWaveform
        }
    }

    var debugSampleRate: Double {
        debugSignal == .respiration ? snapshot.trackingRate : snapshot.frameRate
    }

    var statusText: String {
        if let errorMessage { return errorMessage }
        if !isRunning { return "Tap Start camera." }
        if !snapshot.tracking.faceTracked { return "Looking for a face — sit facing the tablet." }

        switch panel {
        case .tracking:
            let tracking = snapshot.tracking
            if tracking.source == FaceTracker.Source.objectTracking.rawValue {
                return "Landmarks lost — carrying the box on the object tracker."
            }
            return String(
                format: "Tracking: %d landmarks, %d inliers, residual %.2f px",
                tracking.landmarkCount, tracking.inlierCount, tracking.rmsResidualPx
            )
        case .signal:
            if snapshot.quality.clippedFraction > 0.15 { return "Too bright: the skin is over-exposed." }
            if snapshot.quality.roiPixelCount < 500 { return "Move closer to the tablet." }
            if snapshot.quality.secondsBuffered < 6 {
                return String(format: "Acquiring signal… %.0f s", snapshot.quality.secondsBuffered)
            }
            if let snr = snapshot.heartRate?.signalToNoiseDB, snr < 0 {
                return "Weak signal — hold still and avoid backlight."
            }
            return "Measuring."
        }
    }
}
