// Generated by tools/make_swiftpm.py from App/RPPG/Views/SignalPanel.swift — do not edit here.
// The two modules are flattened into one App Playground target, so the
// `import RPPGCore` line has been removed.
import SwiftUI

/// Stage 3+ panel: the ROI mean, the POS chain and the derived rates.
///
/// Kept separate from ``TrackingPanel`` so the tracking work can be verified on its own
/// — the whole point of the staged plan is not to look at heart rates until the box
/// they are measured from is trustworthy.
struct SignalPanel: View {

    @ObservedObject var viewModel: RPPGViewModel

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            metrics
            debugTrace
            posIntermediates
            controls
        }
    }

    private var metrics: some View {
        HStack(spacing: 14) {
            VStack(spacing: 8) {
                MetricCard(
                    title: "Pulse",
                    value: viewModel.heartRateText,
                    unit: "bpm",
                    detail: detail(for: viewModel.snapshot.heartRate),
                    tint: .red
                )
                ConfidenceBar(confidence: viewModel.snapshot.heartRate?.confidence ?? 0, tint: .red)
            }
            VStack(spacing: 8) {
                MetricCard(
                    title: "Respiration",
                    value: viewModel.respirationRateText,
                    unit: "br/min",
                    detail: detail(for: viewModel.snapshot.respirationRate),
                    tint: .cyan
                )
                ConfidenceBar(confidence: viewModel.snapshot.respirationRate?.confidence ?? 0, tint: .cyan)
            }
        }
    }

    private var debugTrace: some View {
        VStack(alignment: .leading, spacing: 8) {
            Picker("Signal", selection: $viewModel.debugSignal) {
                ForEach(DebugSignal.allCases) { signal in
                    Text(signal.rawValue).tag(signal)
                }
            }
            .pickerStyle(.segmented)

            WaveformView(
                samples: viewModel.debugSamples,
                color: viewModel.debugSignal == .respiration ? .cyan : .red,
                visibleSampleCount: max(Int(viewModel.debugSampleRate * visibleSeconds), 2)
            )
            .frame(height: 130)
            .background(Color.black.opacity(0.35), in: RoundedRectangle(cornerRadius: 10))
        }
    }

    /// 8 s of pulse shows four to ten beats; respiration needs far longer to show a cycle.
    private var visibleSeconds: Double {
        viewModel.debugSignal == .respiration ? 45 : 8
    }

    /// Every POS intermediate, live — Stage 5 checkable on the device rather than only
    /// in a CSV afterwards.
    private var posIntermediates: some View {
        let step = viewModel.snapshot.posStep
        return VStack(alignment: .leading, spacing: 6) {
            Text("POS intermediates")
                .font(.caption)
                .foregroundStyle(.secondary)
                .textCase(.uppercase)
            vectorRow("C", step.map { [$0.c.red, $0.c.green, $0.c.blue] })
            vectorRow("Cmean", step.map { [$0.cMean.red, $0.cMean.green, $0.cMean.blue] })
            vectorRow("C./Cmean", step.map { [$0.cNormalized.red, $0.cNormalized.green, $0.cNormalized.blue] })
            vectorRow("S", step.map { [$0.s.first, $0.s.second] })
            vectorRow("Smean", step.map { [$0.sMean.first, $0.sMean.second] })
            vectorRow("Sstd", step.map { [$0.sStd.first, $0.sStd.second] })
            vectorRow("h", step.map { [$0.h] })
            vectorRow("hmean", step.map { [$0.hMean] })
            vectorRow("rPPG", step.map { [$0.rppg] })
            Divider().padding(.vertical, 2)
            vectorRow("ROI px", [Double(viewModel.snapshot.quality.roiPixelCount)])
            vectorRow("clipped %", [viewModel.snapshot.quality.clippedFraction * 100])
            vectorRow("POS steps", [Double(viewModel.snapshot.quality.posStepCount)])
        }
        .font(.caption.monospacedDigit())
        .foregroundStyle(.secondary)
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
    }

    private func vectorRow(_ label: String, _ values: [Double]?) -> some View {
        let text: String
        if let values {
            text = values.map { String(format: "%+.6g", $0) }.joined(separator: "   ")
        } else {
            text = "—"
        }
        return HStack(alignment: .top) {
            Text(label)
                .frame(width: 76, alignment: .leading)
            Text(text)
                .foregroundStyle(.primary)
            Spacer(minLength: 0)
        }
    }

    private var controls: some View {
        VStack(spacing: 12) {
            HStack {
                Text("ROI scale")
                Slider(value: $viewModel.roiScale, in: 0.5...1.0, step: 0.05)
                Text(String(format: "%.2f", viewModel.roiScale))
                    .monospacedDigit()
                    .frame(width: 46, alignment: .trailing)
            }
            Text("1.00 matches the MATLAB reference, which averages the whole rotated box.")
                .font(.caption2)
                .foregroundStyle(.secondary)
                .frame(maxWidth: .infinity, alignment: .leading)

            Toggle("Skin-tone gate inside ROI", isOn: $viewModel.skinGateEnabled)

            Button {
                viewModel.resetSignal()
            } label: {
                Label("Reset signal", systemImage: "arrow.counterclockwise")
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.bordered)
        }
        .font(.callout)
    }

    private func detail(for estimate: SpectralEstimate?) -> String {
        guard let estimate else { return "waiting for signal" }
        return String(
            format: "%.2f Hz · SNR %.1f dB",
            estimate.frequencyHz,
            estimate.signalToNoiseDB.isFinite ? estimate.signalToNoiseDB : 0
        )
    }
}
