// Generated by tools/make_swiftpm.py from Sources/RPPGCore/SignalRecord.swift — do not edit here.
import Foundation

/// One recorded frame: the tracker output, the ROI mean, and **every** POS
/// intermediate.
///
/// This is the backbone of the verification plan. Each stage is checked against this
/// CSV rather than against an impression of the live display:
///
/// * Stage 1 — `dtMs`, `frameCount`
/// * Stage 2 — the four corners, `roll`, `trackSource`
/// * Stage 3 — `roiPixelCount`, `cR/cG/cB`
/// * Stage 5 — everything from `cMean*` to `rppg`, compared with `pos_reference.m`
/// * Stage 6 — `meanCornerY`
public struct SignalRecord: Sendable, Equatable {

    /// Camera frame counter since capture started. Gaps mean dropped frames.
    public var frameCount: Int
    /// Presentation timestamp, seconds.
    public var t: Double
    /// Milliseconds since the previous delivered frame; `nan` on the first frame.
    public var dtMs: Double

    /// Face quad corners in image pixel coordinates, ordered top-left, top-right,
    /// bottom-right, bottom-left in the face's own frame — the same ordering MATLAB's
    /// `bbox2points` produces.
    public var corners: [Point2D]
    /// In-plane rotation, radians, positive clockwise on screen.
    public var roll: Double
    /// `mean(bboxPoints)` in the y axis — the respiration signal.
    public var meanCornerY: Double

    public var roiPixelCount: Int
    /// `detection`, `tracking`, or `none`.
    public var trackSource: String
    public var faceTracked: Bool

    /// The POS step for this frame, if one was produced.
    public var pos: POSProcessor.Step?

    public init(
        frameCount: Int,
        t: Double,
        dtMs: Double,
        corners: [Point2D],
        roll: Double,
        meanCornerY: Double,
        roiPixelCount: Int,
        trackSource: String,
        faceTracked: Bool,
        pos: POSProcessor.Step?
    ) {
        self.frameCount = frameCount
        self.t = t
        self.dtMs = dtMs
        self.corners = corners
        self.roll = roll
        self.meanCornerY = meanCornerY
        self.roiPixelCount = roiPixelCount
        self.trackSource = trackSource
        self.faceTracked = faceTracked
        self.pos = pos
    }
}

/// CSV serialisation for ``SignalRecord``.
///
/// Numbers are written with `%.17g`, which round-trips a `Double` exactly. That is not
/// cosmetic: the whole point of the recording is that replaying the `cR,cG,cB` columns
/// reproduces the `rppg` column bit for bit, and a 6-digit CSV would silently destroy
/// that property.
public enum SignalCSV {

    public static let header = [
        "frameCount", "t", "dtMs",
        "cornerX1", "cornerY1", "cornerX2", "cornerY2",
        "cornerX3", "cornerY3", "cornerX4", "cornerY4",
        "roll", "meanCornerY",
        "roiPixelCount", "trackSource", "faceTracked",
        "cR", "cG", "cB",
        "cMeanR", "cMeanG", "cMeanB",
        "cNormR", "cNormG", "cNormB",
        "s1", "s2", "sMean1", "sMean2",
        "sVar1", "sVar2", "sStd1", "sStd2",
        "h", "hMean", "rppg"
    ]

    public static var headerLine: String { header.joined(separator: ",") }

    /// Formats a `Double` so that parsing it back yields the identical value.
    public static func format(_ value: Double) -> String {
        if value.isNaN { return "nan" }
        if value.isInfinite { return value > 0 ? "inf" : "-inf" }
        return String(format: "%.17g", value)
    }

    public static func line(for record: SignalRecord) -> String {
        var fields: [String] = [
            String(record.frameCount),
            format(record.t),
            format(record.dtMs)
        ]
        for index in 0..<4 {
            let corner = index < record.corners.count ? record.corners[index] : Point2D(x: .nan, y: .nan)
            fields.append(format(corner.x))
            fields.append(format(corner.y))
        }
        fields.append(format(record.roll))
        fields.append(format(record.meanCornerY))
        fields.append(String(record.roiPixelCount))
        fields.append(record.trackSource)
        fields.append(record.faceTracked ? "1" : "0")

        if let pos = record.pos {
            fields.append(contentsOf: [
                format(pos.c.red), format(pos.c.green), format(pos.c.blue),
                format(pos.cMean.red), format(pos.cMean.green), format(pos.cMean.blue),
                format(pos.cNormalized.red), format(pos.cNormalized.green), format(pos.cNormalized.blue),
                format(pos.s.first), format(pos.s.second),
                format(pos.sMean.first), format(pos.sMean.second),
                format(pos.sVar.first), format(pos.sVar.second),
                format(pos.sStd.first), format(pos.sStd.second),
                format(pos.h), format(pos.hMean), format(pos.rppg)
            ])
        } else {
            fields.append(contentsOf: Array(repeating: "", count: 20))
        }
        return fields.joined(separator: ",")
    }

    /// Reads the `cR,cG,cB` columns of a recording, skipping rows with no POS step.
    ///
    /// This is what the replay tool and the golden tests consume: give the same `C`
    /// sequence to Swift and to MATLAB, and the outputs must agree.
    public static func parseChannelTriples(_ text: String) throws -> [ChannelTriple] {
        let rows = try parseRows(text)
        guard let indices = rows.headerIndices(of: ["cR", "cG", "cB"]) else {
            throw CSVError.missingColumns(["cR", "cG", "cB"])
        }
        return rows.values.compactMap { fields in
            guard fields.count > indices.max()!,
                  let red = Double(fields[indices[0]]),
                  let green = Double(fields[indices[1]]),
                  let blue = Double(fields[indices[2]])
            else { return nil }
            return ChannelTriple(red: red, green: green, blue: blue)
        }
    }

    /// Reads one named numeric column.
    public static func parseColumn(_ name: String, from text: String) throws -> [Double] {
        let rows = try parseRows(text)
        guard let index = rows.header.firstIndex(of: name) else {
            throw CSVError.missingColumns([name])
        }
        return rows.values.compactMap { fields in
            guard fields.count > index else { return nil }
            return Double(fields[index])
        }
    }

    // MARK: - Minimal CSV reader

    public enum CSVError: Error, CustomStringConvertible {
        case empty
        case missingColumns([String])

        public var description: String {
            switch self {
            case .empty: return "the CSV is empty"
            case .missingColumns(let names): return "missing column(s): \(names.joined(separator: ", "))"
            }
        }
    }

    struct Rows {
        let header: [String]
        let values: [[String]]

        func headerIndices(of names: [String]) -> [Int]? {
            let indices = names.compactMap { header.firstIndex(of: $0) }
            return indices.count == names.count ? indices : nil
        }
    }

    /// Deliberately simple: no quoting, no embedded commas. The recorder only ever
    /// writes plain numbers and a single lowercase identifier.
    static func parseRows(_ text: String) throws -> Rows {
        var lines = text.split(whereSeparator: \.isNewline).map(String.init)
        lines.removeAll { $0.trimmingCharacters(in: .whitespaces).isEmpty }
        guard let headerLine = lines.first else { throw CSVError.empty }
        let header = headerLine.split(separator: ",", omittingEmptySubsequences: false)
            .map { $0.trimmingCharacters(in: .whitespaces) }
        let values = lines.dropFirst().map { line in
            line.split(separator: ",", omittingEmptySubsequences: false)
                .map { $0.trimmingCharacters(in: .whitespaces) }
        }
        return Rows(header: header, values: values)
    }
}
