#!/usr/bin/env python3
"""Generate RPPG.swiftpm — an App Playground that builds and runs on the iPad itself.

Swift Playgrounds on iPadOS can open a `.swiftpm` package, build it and run it on the
device, with no Mac and no Xcode. That is the only way to get this app onto an iPad
from the iPad, so the sources are mirrored into that layout.

An App Playground is a single executable target, so the two modules are flattened into
one and the now-meaningless `import RPPGCore` lines are dropped. Nothing else is
edited; `Sources/RPPGCore` and `App/RPPG` stay the single source of truth and this
script is re-run whenever they change.

Usage:  python3 tools/make_swiftpm.py
"""

import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
OUT = os.path.join(ROOT, "RPPG.swiftpm")

SOURCE_DIRS = [
    os.path.join(ROOT, "Sources", "RPPGCore"),
    os.path.join(ROOT, "App", "RPPG"),
]

CAMERA_PURPOSE = (
    "The front camera is used to measure pulse and respiration from small colour "
    "changes in the skin. Video is processed on the device and never leaves it."
)

PACKAGE_SWIFT = '''// swift-tools-version: 5.9

// App Playground manifest — open this folder with Swift Playgrounds on iPadOS to
// build and run the app on the device itself.
//
// GENERATED by tools/make_swiftpm.py. Edit Sources/RPPGCore or App/RPPG and re-run
// the script; do not edit the copies in this folder.
//
// `AppleProductTypes` only exists inside Swift Playgrounds, so this manifest does not
// resolve with command-line SwiftPM. That is expected: the root Package.swift is the
// one `swift build` and `swift test` use.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "RPPG",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "RPPG",
            targets: ["AppModule"],
            bundleIdentifier: "com.rppg.tablet",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "%s")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["README.md"]
        )
    ]
)
''' % CAMERA_PURPOSE

README = """# RPPG.swiftpm — iPad에서 바로 빌드·실행

이 폴더는 **Swift Playgrounds(iPadOS)** 로 열면 Mac 없이 아이패드에서 바로 빌드하고
실행할 수 있는 App Playground입니다.

## 아이패드에 받는 법

1. Safari에서 저장소를 열고 **Code ▸ Download ZIP**
2. **파일** 앱에서 받은 zip을 탭해 압축 해제
3. `RPPG.swiftpm` 을 탭 → Swift Playgrounds가 열림
4. 오른쪽 위 **▶︎** 로 실행 (첫 실행 때 카메라 권한 허용)

> 시뮬레이터가 아니라 아이패드 실기기에서 도는 것이므로 카메라가 실제로 동작합니다.

## 이 폴더는 생성물입니다

`tools/make_swiftpm.py` 가 `Sources/RPPGCore` 와 `App/RPPG` 를 여기에 복사합니다.
App Playground는 단일 타깃이라 두 모듈을 하나로 합치고 `import RPPGCore` 줄만 제거합니다.

**여기 있는 파일을 직접 고치지 마세요.** 원본을 고치고 스크립트를 다시 돌리면 됩니다:

```bash
python3 tools/make_swiftpm.py
```

유닛 테스트(`swift test`)와 `rppg-replay` 는 저장소 루트의 `Package.swift` 를 씁니다.
이 매니페스트는 Swift Playgrounds 전용(`import AppleProductTypes`)이라
명령줄 SwiftPM으로는 열리지 않습니다.
"""


def swift_files(directory):
    found = []
    for base, _, names in os.walk(directory):
        for name in sorted(names):
            if name.endswith(".swift"):
                found.append(os.path.join(base, name))
    return sorted(found)


def flatten(text, origin):
    """Drop the cross-module import and stamp where the file came from."""
    lines = text.splitlines()
    had_import = any(line.strip() == "import RPPGCore" for line in lines)
    lines = [line for line in lines if line.strip() != "import RPPGCore"]

    header = "// Generated by tools/make_swiftpm.py from %s — do not edit here.\n" % origin
    if had_import:
        header += (
            "// The two modules are flattened into one App Playground target, so the\n"
            "// `import RPPGCore` line has been removed.\n"
        )
    return header + "\n".join(lines).rstrip() + "\n"


def main():
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    written = []
    seen = {}
    for directory in SOURCE_DIRS:
        for path in swift_files(directory):
            name = os.path.basename(path)
            origin = os.path.relpath(path, ROOT)
            if name in seen:
                raise SystemExit(
                    "duplicate file name %s (%s and %s) — the flat App Playground "
                    "layout needs unique names" % (name, seen[name], origin)
                )
            seen[name] = origin
            with open(path) as handle:
                text = handle.read()
            with open(os.path.join(OUT, name), "w") as handle:
                handle.write(flatten(text, origin))
            written.append(name)

    with open(os.path.join(OUT, "Package.swift"), "w") as handle:
        handle.write(PACKAGE_SWIFT)
    with open(os.path.join(OUT, "README.md"), "w") as handle:
        handle.write(README)

    print("wrote %s" % os.path.relpath(OUT, ROOT))
    print("  %d Swift files + Package.swift" % len(written))
    for name in written:
        print("    %s" % name)


if __name__ == "__main__":
    main()
